### ISSUE TITLE
--json option isn't supported

### ISSUE THREAD

**Issue by yurivict** [vermaden/lsblk#8]
The rpi-imager expects the ```--json``` option [here](https://github.com/raspberrypi/rpi-imager/blob/qml/src/CMakeLists.txt#L343) but it isn't supported.

**Comment by vermaden** [comment]
Hi,

the `lsblk(8)` supports either the default output or the devices list with `-d` option.

Hope that helps.

Regards,
vermaden

**Comment by yurivict** [comment]
Thanks,

Yuri
